# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY=y

# Hardware-specific for AliExpress Receiver
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y

# RC Oscillator calibration
CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_LF_ALWAYS=y
CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_LF_PERIOD=1

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILTIN=y
CONFIG_ZMK_DISPLAY_CONTRAST=128
CONFIG_ZMK_DISPLAY_FULL_REFRESH_PERIOD=300
