# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY=y

# Hardware-specific for AliExpress Receiver
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_250PPM=y

# RC Oscillator calibration
CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_LF_ALWAYS=y
CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_LF_PERIOD=1

# ZMK Dongle Display settings
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=y
